# Generated by Django 4.2.1 on 2023-05-23 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_beautysalons'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetBookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookieName', models.CharField(blank=True, max_length=50, null=True)),
                ('bookieEmail', models.CharField(blank=True, max_length=50, null=True)),
                ('bookieContactNo', models.CharField(blank=True, max_length=20, null=True)),
                ('bookieAdress', models.CharField(blank=True, max_length=100, null=True)),
                ('hairCut', models.CharField(blank=True, max_length=50, null=True)),
                ('hairTreatment', models.CharField(blank=True, max_length=50, null=True)),
                ('skinTreatment', models.CharField(blank=True, max_length=50, null=True)),
                ('extension', models.CharField(blank=True, max_length=50, null=True)),
                ('package1', models.CharField(blank=True, max_length=50, null=True)),
                ('package2', models.CharField(blank=True, max_length=50, null=True)),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('bookieUsername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.registeruser')),
                ('parlor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.beautysalons')),
            ],
            options={
                'verbose_name': 'Salon Booking Details',
            },
        ),
    ]
