# Generated by Django 4.2.1 on 2023-05-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_getbookingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='getbookingdetails',
            name='facial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
